### ISSUE TITLE
可以编译个M1 arm64的版本吗?

### ISSUE THREAD

**Issue by jiayouzl** [chrisxiao/TrojanA#10]
谢谢

**Comment by chrisxiao** [comment]
感谢反馈，不好意思，目前我没有M1芯片的机器，暂时提供不了。如果你有的话，可以自己构建一个。
具体步骤：
拉取该项目的代码，在项目根目录下执行:

`python -m pip install -r requirements-build.txt`

`python setup.py py2app`

执行完毕会在 `dist` 目录生成构建好的应用文件

**Comment by chrisxiao** [comment]
最新的版本已经支持了
