### ISSUE TITLE
怎么在终端之类的地方配置代理呢?

### ISSUE THREAD

**Issue by zohar-soul** [chrisxiao/TrojanA#12]
我目前的基本配置是 local_port=1081
在这个配置的情况下
终端设置 export https_proxy=http://127.0.0.1:1081 http_proxy=http://127.0.0.1:1081  没有效果...

```
curl https://google.com -v
* Uses proxy env variable https_proxy == 'http://127.0.0.1:1081'
*   Trying 127.0.0.1:1081...
* Connected to 127.0.0.1 (127.0.0.1) port 1081 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to google.com:443
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.79.1
> Proxy-Connection: Keep-Alive
> 
* Proxy CONNECT aborted
* CONNECT phase completed!
* Closing connection 0
curl: (56) Proxy CONNECT aborted
```

非常感谢作者的付出

**Comment by zohar-soul** [comment]
> 代理地址的前缀要改成 “socks5”，比如 “socks5://127.0.0.1:1081” `export http_proxy=socks5://127.0.0.1:1081` `export https_proxy=socks5://127.0.0.1:1081` 可以试试

可以了 多谢大佬. 
另外还有个问题是, 在pac模式下访问 google 等无法打开, 但是在全局模式下是ok的.
已尝试过 `从gfwlist更新pac` , 有可能是哪方面的原因导致的呢?

**Comment by chrisxiao** [comment]
浏览器上可以访问吗？

**Comment by zohar-soul** [comment]
> 浏览器上可以访问吗？ 排查思路：
> 
> 1. 先确定代理服务可以工作
> 2. 再确定curl是否有问题

1. 浏览器上是ok的
2. 我猜测是 curl 可能不支持 socket5 代理, 但是不知道 Trojan 的 http 代理端口是多少?

**Comment by chrisxiao** [comment]
curl 是支持 socks5 代理的，可以换其他网站试试看，先在浏览器中确定可以正常访问，再用curl试，可以分别测试一下http、https的网站

Trojan 本身就只是 socks 代理，不支持http代理。

**Comment by zohar-soul** [comment]
> curl 是支持 socks5 代理的，可以换其他网站试试看，先在浏览器中确定可以正常访问，再用curl试，可以分别测试一下http、https的网站
> 
> Trojan 本身就只是 socks 代理，不支持http代理。

好的
