### ISSUE TITLE
用一段时间之后就失效了

### ISSUE THREAD

**Issue by KlawLee** [chrisxiao/TrojanA#3]
首先，感谢提供了这个工具，在我一开始使用的时候，很顺利地成功fq了，用一段时间之后，打开之后，配置什么也没动，另外，这个节点在我手机是可以正常使用的，而mac上却失效了，不知道什么原因导致的。

**Comment by chrisxiao** [comment]
收到反馈，可以试下，先关闭服务，退出应用，然后再从新打开，再开启服务试试

**Comment by chrisxiao** [comment]
无进一步反馈，先关闭
